### ISSUE TITLE
Wrong version in custom_updater

### ISSUE THREAD

**Issue by Shponzo** [ljmerza/calendar-card#1]
Hi,

First of all, thank you very much for updating this calendar card!
I just installed it, but the custom_updater still gives me version 1.1.0, but 1.2.1 is already installed.

When I go to https://raw.githubusercontent.com/ljmerza/homeassistant-lovelace-google-calendar-card/master/custom_updater.json I see that it gives me  "version": "1.1.0".

Is this something you have to change?

Thanks!

**Comment by ljmerza** [comment]
Hey, thanks for notifying me. I've updated the custom_updater.json file. It was still referencing an old repo
