### ISSUE TITLE
Plans To Add Progress Bar/Color

### ISSUE THREAD

**Issue by zerox1212** [ljmerza/calendar-card#10]
I like that the new version actually works. :) However is there any plan to put the colors and progress bar back in?

The progress bar was a nice touch to quickly see where I'm at in my schedule.

**Comment by ljmerza** [comment]
I can add the progressBar. I could never get the colors to work doesn't seem like something Google supports anymore. Were you able to get it to work on the old calendar card?

**Comment by zerox1212** [comment]
I only saw the progress bar, but colors would be awesome. I haven't looked at the Google Calendar API in a long time though.

**Comment by ljmerza** [comment]
Ok I added support for a progressBar in 2.1.0

**Comment by zerox1212** [comment]
Thanks for the great work!
