### ISSUE TITLE
0.110 log error re 'CustomElementRegistry'

### ISSUE THREAD

**Issue by IanAdd** [ljmerza/calendar-card#101]
http://homeassistant.local:8123/hacsfiles/calendar-card/calendar-card.js?v=1.3:826:220 Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "calendar-card-editor" has already been used with this registry

Is this me using two cards with calendar ? Or is it you ?

**Comment by ljmerza** [comment]
looks like you've added it twice check you lovelace settings
