### ISSUE TITLE
Modify size of the progress bar

### ISSUE THREAD

**Issue by jankete** [ljmerza/calendar-card#105]
Hi, is there any way to change the size of the dot on the progress bar? It looks much too big on my setup:
![image](https://user-images.githubusercontent.com/22338766/82986518-45339100-9ff6-11ea-8536-23b7c7b166ac.png)

**Comment by noxhirsch** [comment]
It should be fixed with https://github.com/ljmerza/calendar-card/pull/103

**Comment by ljmerza** [comment]
fixed in v3.108.7
