### ISSUE TITLE
Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale.

### ISSUE THREAD

**Issue by Sjeff** [ljmerza/calendar-card#109]
Error logged while debugging with Chrome:
  - Home Assistant Version 0.112.3
  - Chrome Version 83.0.4103.116
  - Home Assistant Supervised (Ubuntu Docker & Raspbian Docker)

Chrome debugging message:
![image](https://user-images.githubusercontent.com/11430228/86745832-e9b7e280-c03a-11ea-9a83-7a2a99610af1.png)

**Comment by ljmerza** [comment]
fix in v3.109.1
