### ISSUE TITLE
SyntaxError: expected expression, got '<'

### ISSUE THREAD

**Issue by salikmichal** [ljmerza/calendar-card#14]
I can't load calendar card. Notice that it's my first use of this addon. Raspberry Pi, Hass.io. 0.86.2 

Custom element doesn't exist: calendar-card.

{
  "type": "custom:calendar-card",
  "title": "My Calendar",
  "numberOfDays": 14,
  "progressBar": true,
  "entities": [
    "calendar.xxxxx
  ]
}

I get following error in HA logs.

/local/custom-lovelace/calendar-card/calendar-card.js?track=true:7:0 SyntaxError: expected expression, got '<'

  - url: /local/custom-lovelace/calendar-card/calendar-card.js?track=true
    type: js

**Comment by iantrich** [comment]
You didn't download the file properly

**Comment by salikmichal** [comment]
OK you probably have to add all files to the directory not only calendar-card.js It works.

Instruction says:

"Download `calendar-card.js` from the [latest release](https://github.com/ljmerza/calendar-card/releases/latest) and upload it your /www folder of your Home Assistant config directory. "

Close issue please.

**Comment by iantrich** [comment]
That is the only file you need, you just didn't download it properly, so you got HTML instead of raw Javascript in the file.
