### ISSUE TITLE
Map icon still showing even after showLocation: False

### ISSUE THREAD

**Issue by richardmayo** [ljmerza/calendar-card#18]
Hi,

I have set `showLocation: false` in the yaml file, but the map icon is still showing. Anyway to disable that too?

Thanks

**Comment by richardmayo** [comment]
Hi,

I have set `showLocation: false` in the yaml file, but the map icon is still showing. Anyway to disable that too?

Thanks

**Comment by ljmerza** [comment]
`showLocation` only removes the address link. I just added `showLocationIcon` option so you can hide the icon as well. It's in version 3.5.0
