### ISSUE TITLE
Fully Kiosk Browser - Custom element doesn't exist

### ISSUE THREAD

**Issue by abien** [ljmerza/calendar-card#19]
Using the Android App "_Fully Kiosk Browser_" to display HA UI on a Amazon Fire Tablet 10.
It will throw a red box with "`Custom element doesn't exist: calendar-card.`"
HA logfile will show: 
`<my.ip>:8123/customcards/calendar-card.js:74:1541 Uncaught SyntaxError: Unexpected token ...`
This error msg will only appear in the Fully Kiosk Browser app. Everything works fine on other browsers on other devices. This also does not seem to be specific to this card - almost no custom card renders successfully on this device.
I am wondering if anyone here might have any clues as to whats causing this, how to solve this or even just a hint about a different way/app to display HA on the tablet.

**Comment by iantrich** [comment]
@abien fire tablets have a very old version of webview, that's the problem. Custom cards would need to be built with babel, probably, to provide the polyfills necessary to render them on older devices as HA core does. Does [mini-media-player](https://github.com/kalkih/mini-media-player) work for you? I believe it is bundled with babel.

**Comment by ljmerza** [comment]
I've thought about adding babel but it would add so much to the code size. I'm surprised home assistant even works on older browsers.

**Comment by abien** [comment]
@iantrich Well - no. [mini-media-player](https://github.com/kalkih/mini-media-player) does not work any better. I guess i bought the wrong kind of tablet _sigh_.
I know this is OT - but: Any recommendations on the low-budget tablet? Or advise on what i should look out for to ensure it works well with HA?
Also: [mini-media-player](https://github.com/kalkih/mini-media-player) = Did not know about this card before. Very nice 👍

**Comment by iantrich** [comment]
Fire tablets are so freaking cheap, that's the problem and a 10" fire tablet is perfect for a home interface. How much size does babel add? Maybe we could have different distributions? Or at least provide instructions to people on how they could build a card with babel?

**Comment by iantrich** [comment]
@abien checkout sharethelove.io for a good list of custom cards.

I'm using a x230 as my HA installation and interface :man_shrugging: It's okay, nothing spectacular, but can run full Linux on it so no issues with browsers.

**Comment by ljmerza** [comment]
@iantrich Not sure for this card. It's already massive from adding localization. I'll look into it sometime this week though. I hope to add the edit card for this soon.

**Comment by abien** [comment]
My issue might not be related to anything on the coding side at all.
- Tablet's own Amazon Silk Browser renders with no errors
- Google Chrome renders with no errors
- Fully Kiosk Browser gives errors

_(Problem with both working browser is that they don't completely fullscreen and lack some other nice to have functions that Fully Kiosk offers)_

I am guessing it's related to the kiosk browser app, it is using an old webview (v 59.x)
Just found their [FAQ](https://www.ozerov.de/fully-kiosk-browser/de/) where it specifically states: "_The Android Webview can’t be updated separately, but it seems to be updated with Fire OS and is slightly outdated (version 59 vs. current ver. 70) with Fire OS I tested._"

Maybe this is a wontfix/cantfix? :)

**Comment by iantrich** [comment]
I thought fully used the installed webview? Are you saying they are packaging the app with it's own version of webview?

**Comment by abien** [comment]
I assume so - but i really should't comment. 48h ago i would have though webview must be a web based team-viewer tool. I did ask Alexey (from Fully-Team) about this and he replied to me:

> We still don't know any means to upgrade the Webview separately on Fire OS. It will be upgraded by the next Fire OS upgrade but is always behind the latest Webview.

Not sure how that fits into the whole "But it works in all other browsers" thing - thats above me.

**Comment by ljmerza** [comment]
@abien I added babel support to 3.6.0 so let me know if it works now.

**Comment by iantrich** [comment]
Curious to hear results on this. Will likely do the same for all my cards if it does work

**Comment by abien** [comment]
I update the card. cleared the caches etc - no change. The custom element will not be displayed :(

**Comment by ljmerza** [comment]
Weird I left babel at default which should compile to es5.  This is what home assistant does and the default cards work. Ill look further into it but I don't have a kindle to test.  If there's a way for you to find the actual error that'd help. Even if the card works I'm worried about the CSS cause I use flexbox.

**Comment by ljmerza** [comment]
ok try this version and let me know what the error is. The initial error you gave was object spreading but I added support for that in the current version. You might have new errors. I tried to see what version of webview the kindle has but couldn't find anything.  Here's the link

https://raw.githubusercontent.com/ljmerza/calendar-card/master/calendar-card.js

**Comment by abien** [comment]
I tried two times to make 100% sure i don't render a cached version, hence the `?v=98783` on the second try.

Log output: 
```2019-04-10 16:02:40 ERROR (MainThread) [frontend.js.es5.201903310] http://192.168.0.12:8123/customcards/calendar-card.js:489:375 Uncaught SyntaxError: Unexpected token ...
2019-04-10 16:13:32 ERROR (MainThread) [frontend.js.es5.201903310] http://192.168.0.12:8123/customcards/calendar-card.js:489:375 Uncaught SyntaxError: Unexpected token ...

2019-04-10 16:19:46 ERROR (MainThread) [frontend.js.es5.201903310] http://192.168.0.12:8123/customcards/calendar-card.js?v=98783:489:375 Uncaught SyntaxError: Unexpected token ...
2019-04-10 16:20:17 ERROR (MainThread) [frontend.js.es5.201903310] http://192.168.0.12:8123/customcards/calendar-card.js?v=98783:489:375 Uncaught SyntaxError: Unexpected token ...
```

**Comment by ljmerza** [comment]
Can you tell me what fire os version you have? I installed android studio so i can emulate a fire tablet to find what the issue is. Looks like the latest version you can do on that is fire os v5.3.6.4

**Comment by iantrich** [comment]
The part that bugs me about all of this that on the one device, Silk and Chrome work, but Fully doesn't with the same Webview version...

**Comment by ljmerza** [comment]
Yeah just tired android 5.1 but i cant even get ha to load at all

**Comment by iantrich** [comment]
i got my hands on my neighbors fire hd 8 (6th gen) running fire os 5.3.6.4 (android 5.1.1) and I too am able to bring up custom cards in silk and chrome, but not fully.

**Comment by iantrich** [comment]
I've had this thing for 20 minutes now and officially hate it. I understand why they are so inexpensive...

**Comment by ljmerza** [comment]
https://play.google.com/store/apps/details?id=com.thanksmister.iot.wallpanel&rdid=com.thanksmister.iot.wallpanel looks promising

**Comment by abien** [comment]
tested wallpanel - does not render custom elements. same as fully kiosk app.

**Comment by ljmerza** [comment]
Ok can you both try this one? https://raw.githubusercontent.com/ljmerza/calendar-card/master/calendar-card.js

**Comment by iantrich** [comment]
this version is grinding the vscode add-on to a halt...weird...

**Comment by ljmerza** [comment]
Add on?

**Comment by iantrich** [comment]
https://github.com/hassio-addons/addon-vscode/blob/v0.2.0/README.md

New version does not work on FKB for me :( This app is being difficult

**Comment by ljmerza** [comment]
ah yeah I saw that the other day. I don't use hass.io but it would be nice to have vscode in the browser. Usually the addons are just wrappers over existing dockerfiles but this one is custom made for hass

**Comment by iantrich** [comment]
No, it is just a wrapper as well. It has the vscode plugin for HA pre-installed which is perhaps what you're thinking of

**Comment by iantrich** [comment]
Tried just following this https://lit-element.polymer-project.org/guide/publish with no luck on my podcast-card

**Comment by ljmerza** [comment]
does the current master version not work at all? it started working no apple phones again thankfully so one step closer

**Comment by iantrich** [comment]
It works everywhere but FKB, in my testing

**Comment by ljmerza** [comment]
well, I have `> 0.25%, not dead` set as the target which is

```
{
  "android": "4.4.3",
  "chrome": "49",
  "edge": "17",
  "firefox": "64",
  "ie": "11",
  "ios": "8",
  "opera": "57",
  "safari": "11.1",
  "samsung": "4"
}
```

Think I saw the latest FireOS is Android `4.4.1` and it's at  `4.4.3` sooo not sure. Anyone can post the console error?

**Comment by iantrich** [comment]
I put the latest master release on and enabled remote debugging but unfortunately there are no errors. Of the 7 custom cards I have on this view, 3 produced errors.

`Uncaught SyntaxError: Unexpected token ...`

🤷‍♂️

**Comment by abien** [comment]
FYI: Something happened, all custom cards (including calendar) no longer show any error and instead display just fine. I assume something in FireOS has been updated but i haven't had time to look into the details yet.

**Comment by iantrich** [comment]
What?!? Lol. I'm out of town this weekend but will check when I get home.

**Comment by iantrich** [comment]
I forgot about this, I made a note to myself to test this tonight

**Comment by iantrich** [comment]
No change here. 
Webview version 59
FKB version 1.30
Fire OS 5.3.6.4

**Comment by iantrich** [comment]
@abien can you check your Fire OS version?

**Comment by abien** [comment]
FireOS 5.6.4.0
FKB 1.30
Webview 70.0.3538.110

**Comment by abien** [comment]
Since the original reason for this is solved for me - i am closing this.

**Comment by scstraus** [comment]
> FireOS 5.6.4.0
> FKB 1.30
> Webview 70.0.3538.110

Are you saying you somehow managed to get Webview 70 onto the Kindle Fire with FKB? I have a much newer kindle version and fkb version and still have webview 59.. How'd you do it?
FireOS: 6.3.0.1
FKB: 1.33-fire
Webview: 59.0.3071.125

**Comment by abien** [comment]
I didn't do anything. After some kind of auto-update overnight these were just the versions i have now.

**Comment by scstraus** [comment]
Oh cool, my auto update came in too and now all my custom cards finally work. I guess the solution is just “wait and see” at least with the new 2018 kindles.
