### ISSUE TITLE
Calendar crashes since last update.

### ISSUE THREAD

**Issue by jimz011** [ljmerza/calendar-card#20]
Hi, since the update from yesterday whenever I open the calendar on my iphone the HA app will just hang time out and restart. This was never a problem before.

It works as expected on my desktop though. I use a pop up card to show the calendar which worked fine til yesterdays update. Not a big deal but I thought you should know.

**Comment by ljmerza** [comment]
What version of the iPhone do you have?  I single cards shouldn't crash all of HA. Did you try to clear cache?

**Comment by jimz011** [comment]
iPhone X, latest iOS (12.3). Nah it doesn’t crash Home Assistant, just the app. However I use a pop up card which might cause it though. Will test it tonight on a standard view tab. Cache is cleared, so that shouldn’t be the problem. If I wait long enough (like 5 minutes) the calendar will eventually pop up, but in the meantime the entire app is unresponsive. I can either wait the 5 minutes or force close the app.

It has always worked fine until the update from yesterday. I just mentioned it here as maybe someone else has the same problem. But it might be caused by many factors (I use ios HA app 2.0 and a beta of ios, so it could be the problem).

I will test some different configurations tonight with different apps to see what causes it.

Edit: just tried it in safari, same behaviour. Will try a non pop up card tonight (unfortunately I do not have a computer at my disposal atm)

Edit2: Tried putting the calendar-card in a view with the only card present without any other custom cards on top (e.g. card-modder) and the behaviour is still the same. I have redownloaded the file and tried it again, restarted HA several times, cleared cache on iphone (as far as that is possible), I have tried enabling all experimental features in safari to see if that would make a difference, I even went as far as resetting the HA app. still nothing. Weird thing is, on chrome/firefox for windows it works without a problem and there too I have cleared cache several times just to be sure. I see the new card differs a lot in code from the previous ones (as in I can no longer read the file with the standard ubuntu text editor, opening it in notepad++ gave better results but a lot of lines added compared to the old version.)

Anyways reverted back to the previous version and all is working fine again.

**Comment by stast1** [comment]
I also have problems with the new card. Chrome works fine, and Maxthon freezes. The old version worked without fail.

**Comment by ljmerza** [comment]
yeah sorry. this new one has no changes just trying to support more browsers. looks like i botched it though. i wont be making any new changes until i figure it out though so you can safely use the old version.

**Comment by ljmerza** [comment]
Can you try this one to see if it works? https://raw.githubusercontent.com/ljmerza/calendar-card/master/calendar-card.js

**Comment by jimz011** [comment]
@ljmerza This version seems to work.

**Comment by ljmerza** [comment]
awesome. I'm going to verify a few more things before i officially update but should be soon. thanks
