### ISSUE TITLE
Map Icon URL not linking the full address

### ISSUE THREAD

**Issue by Babinyecz** [ljmerza/calendar-card#25]
In the calendar-card.js file, this is line 695:
`      <a href="https://www.google.com/maps?daddr=${e.locationAddress}" target="_blank" rel="nofollow noreferrer noopener"`

If seems to only show the City and Zip code in google maps when you click on the URL.  I was able to fix it by modifying that line to be this:
`      <a href="https://www.google.com/maps?daddr=${e.location} ${e.locationAddress}" target="_blank" rel="nofollow noreferrer noopener"`

I'm sure you have a prettier way of doing that, but I wanted to let you know.  Thanks.

**Comment by ljmerza** [comment]
updated in v3.10.2 thanks!

**Comment by Babinyecz** [comment]
Thanks for the quick update!
