### ISSUE TITLE
Show calendar event is from

### ISSUE THREAD

**Issue by TheLastProject** [ljmerza/calendar-card#30]
Hey again,

I have several calendars in it, and I'd like to know what events are for work and which aren't, thus I'd like to see the event name displayed too

I'm totally willing to implement this myself, I just need a pointer: is there a way to add a field to the event from the source calendar? I think the entity friendly_name probably gets lost at https://github.com/ljmerza/calendar-card/blob/master/src/index.js#L157-L161, but I have no clue how Promises, mapping and reducing works in JavaScript, so I'm not sure how to try to make sure I can make sure I'll have the calendar name in the event. If you can tell me how to do that, I'm sure I can figure out the rest myself.

**Comment by ljmerza** [comment]
I'm not sure what you mean by event name. The calendar events are retrieved by home assistant and the card just gets whatever data home assistant has. If you look at the response for the network calls when getting the calendars there are only properties for `description` and `summary`. If there IS something missing from these calendar objects on the return JSON then the code on the backend of home assistant would have to be changed to add that data.

![image](https://user-images.githubusercontent.com/4085765/58572689-2bf0dc80-820a-11e9-8897-d0a75c4c7be8.png)

**Comment by TheLastProject** [comment]
Oops, I meant "calendar name for each event". Sorry!

**Comment by ljmerza** [comment]
added `showEventOrigin` support in 3.11.0
