### ISSUE TITLE
Missing last entry for the day (TZ related)

### ISSUE THREAD

**Issue by theOrakle** [ljmerza/calendar-card#36]
So I came across an issue and I really can't limit it down more than the title states.

Here is my card config that fails:
```
type: custom:calendar-card
title: Today
numberOfDays: 1
timeFormat: hh:mm A
showEventOrigin: true
showLocationIcon: false
showMultiDay: true
startFromToday: true
entities:
  - calendar.boys
  - calendar.wiesalani
```

Here Is what I see:
![image](https://user-images.githubusercontent.com/37029980/61873461-a9a03400-aeab-11e9-9eee-e55100c06601.png)

Change the numberOfDays to 2:
```
type: custom:calendar-card
title: Today
numberOfDays: 2
timeFormat: hh:mm A
showEventOrigin: true
showLocationIcon: false
showMultiDay: true
startFromToday: true
entities:
  - calendar.boys
  - calendar.wiesalani
```

And now what I see:
![image](https://user-images.githubusercontent.com/37029980/61873647-0f8cbb80-aeac-11e9-809e-74bdf6ca80cd.png)

The "G3 Conditioning activities" is missing... Here is what the event looks like:
![image](https://user-images.githubusercontent.com/37029980/61873831-80cc6e80-aeac-11e9-857a-46a49fad3140.png)

**Comment by ljmerza** [comment]
I tried creating similar events and I couldn't reproduce this. I see you have `showMultiDay: true` but if an event is multiday then it'll show what day it is in in the event's title. the 25th would show `G3 conditioning activities (1/2)` and the 26th would show `G3 conditioning activities (2/2)`. 

Now that I look at it again, your event starts on the 25th at 7 and ends an hour later on the 25th at 8 so it's showing correctly?

**Comment by theOrakle** [comment]
I did a bit more testing and narrowed it down.  Sorry for misleading you earlier.

It doesn't show any event after 7PM.  Is this a Google setting I have that I cannot find?

![image](https://user-images.githubusercontent.com/37029980/62165356-ddcc8800-b2e3-11e9-9326-0ac2f1fae8dc.png)

Shows like:
![image](https://user-images.githubusercontent.com/37029980/62165377-eae97700-b2e3-11e9-941a-774c57298a8d.png)

And...

![image](https://user-images.githubusercontent.com/37029980/62165406-fe94dd80-b2e3-11e9-9fd8-c6661f9cd6d7.png)

Shows like:
![image](https://user-images.githubusercontent.com/37029980/62165431-0c4a6300-b2e4-11e9-81f8-4d518ed780f4.png)

**Comment by theOrakle** [comment]
My Timezone is CST (CDT) - I think that maybe coming into play here.

**Comment by agesly** [comment]
I believe the easiest way to solve this would require migrating from [`moment`](https://momentjs.com/) to [`luxon`](https://moment.github.io/luxon/).
I don't think [`moment-timezone`](https://momentjs.com/timezone/) does the job. But I might be wrong.

**Comment by davidmonro** [comment]
I _think_ I'm seeing the same problem. I have a meeting from 10:00 to 11:00 today that isn't showing up; my timezone is AEDT (UTC+11:00). If I move the end time to something else, I can see it. So is it something to do with the end time being 00:00 UTC?

**Comment by ljmerza** [comment]
try version 3.108.2 so see if this is still an issue

**Comment by theOrakle** [comment]
That fixed it for me...  Thank you.
