### ISSUE TITLE
Feature Request: Elegant reload

### ISSUE THREAD

**Issue by noxhirsch** [ljmerza/calendar-card#44]
I have a feature request (because I don't really know how to implement this one):
It would be great if the reload of the calendar doesn't remove all content and loads it back again. The better solution in my opinion is to load in background (maybe show the loading circle in a corner - but I think that no loading circle is needed) and then refresh the content in one go.
If you have the calendar on a dashboard like me, all the content below jumps up and down again with every refresh.

**Comment by ljmerza** [comment]
The problem with this is the calendar card has to fetch it's data. All other cards just get the data from HA when created. When you switch tabs the card is destroyed and needs to be recreated each time. Before the loading screen, the card would just be blank as it went to fetch the calendar data. 

I did try to include calendar events in the sensor itself but it was pushed back and I eventually gave up on that. There may be a round about way of saving data in local storage and just getting that first while refreshing in the background but then you'll be seeing old calendar data while the new data is fetched so it's a trade off I'm not sure I want to make.

Ultimately, to fix this the calendar events need to be included in the calendar sensor in HA itself.

**Comment by noxhirsch** [comment]
I can totally understand the problem here. And I agree that including the events into the HA sensor would be the best solution (maybe a custom component everyone can load via HACS would be an alternative if the maintainers of HASS don't want it in the main calendar sensor).
But just to clarify what I meant in my feature request: I didn't mean the loading of the events when opening a view with a calendar card. I meant the reloading that happens if you have a tab/view opened for a longer period of time (like I do with my dashboards). Then the events disappear for two seconds and appear again (refreshed). This causes flashing of the screen (because of the jumping cards) and make everyone look on the dashboards thinking that something happend.
Because this isn't really old calendar data (unlike your example where the cached data could be hours/days old) I don't think it's a trade off here. As far as I can imagine, the data doesn't even have to be cached - so calendar card checks if this is the first load or a reload (I think in the latter case there should be the old data stored in variables). If it's the first load it presents the loading circle to the user - if it's a reload it just replaces the card content directly with the new data, when the data is ready (instead of replacing it with an loading circle first).
I hope you can understand what I mean - sorry my English isn't that good, but I try my best ;)

**Comment by ljmerza** [comment]
ok I got this working in v3.91.2

**Comment by noxhirsch** [comment]
Oh, you're amazing! Thank you very much for your effort!
