### ISSUE TITLE
Missing Google Reminders

### ISSUE THREAD

**Issue by zappasmart** [ljmerza/calendar-card#46]
Google Calendar automatically creates a system calendar for Google Reminders. The Reminders calendar is not exposed to this card.

![image](https://user-images.githubusercontent.com/53600373/64323447-ce1c1f80-cfc4-11e9-90a7-9412217a3955.png)

**Comment by ljmerza** [comment]
Reminders aren't included in the Home Assistant Google Calendar Integration. If you want those added it'd have to be through Home Assistant as that's where this card gets its events.

https://github.com/home-assistant/home-assistant

**Comment by zappasmart** [comment]
It seems to be a missing feature from Google Calendar APIs, reminders are not handled:
https://issuetracker.google.com/issues/36760283
