### ISSUE TITLE
Any way to ignore selected calendar entries

### ISSUE THREAD

**Issue by IanAdd** [ljmerza/calendar-card#47]
I use an airbnb calendar. This calendar annoyingly includes an entry for the current snd next day saying it is blocked (ie unbookable). 
To deal with this I want be able exclude showing a calendar entry if it contains a specific string.
Any chance ? Any workarounds?
ian

**Comment by ljmerza** [comment]
ok added this in `v3.94.0` as `ignoreEventsExpression` input. It's case insensitive an example is if you want to ignore all events with `airbnb` in the title just set `ignoreEventsExpression` to `airbnb`. Let me know if that works out for you.

**Comment by IanAdd** [comment]
Awesome, it did what I wanted. !!
However, any chance it could be a regex so people could use patterns and, more likely, or conditions to exclude more than one type.

**Comment by ljmerza** [comment]
it should be a regex just case insensitive

**Comment by IanAdd** [comment]
I tried (not available) including the brackets which are part of the string
i want to define. This worked.

I then tried (not available)|blocked to exclude an entry with the word
blocked in it and it no longer hid any entry. What am I doing wrong?

Ian

**Comment by IanAdd** [comment]
Apologies, I worked it out !
((not available)|blocked)
Ian

**Comment by IanAdd** [comment]
Hi

For no apparent reason/action by me, my two calendar cards have stopped
working. They just show the heading and the progress circles going round
and round. I've changed nothing in them.

I'm running 0.993

Any thoughts?

Ian

**Comment by ljmerza** [comment]
is the calendar sensor working? The card gets its data from that

**Comment by IanAdd** [comment]
Hi

Thanks for responding.

Not sure how to test what you are asking.

I have the google_calendar.yaml file untouched.
Your card refers to entity not sensor?

I have tried the service 'google.found_calendar' and it reports: failed to
call service google/found_calendar. 'id'
In the developer tools log it says:

Log Details (ERROR)

Tue Oct 01 2019 16:36:21 GMT+1000 (Australian Eastern Standard Time)

'id'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py",
line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1261, in
_execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/google/__init__.py",
line 233, in _found_calendar
    calendar = get_calendar_info(hass, call.data)
  File "/usr/src/homeassistant/homeassistant/components/google/__init__.py",
line 360, in get_calendar_info
    CONF_CAL_ID: calendar["id"],
KeyError: 'id'
