### ISSUE TITLE
Unnecessary reload

### ISSUE THREAD

**Issue by caro-coder** [ljmerza/calendar-card#48]
I noticed that the calendar disappears sometimes and reappear like it would on a card reload, but there are no changed events.
It would be better if the card checks if anything has changed before triggering a reload.

Thank you in advance!

**Comment by timdonovanuk** [comment]
This card seems to be the biggest source of page load issues for me. I quite often load my dashboard and am met with a loading icon in place of the calendar events.

**Comment by ljmerza** [comment]
how often does this happen? The card should only be fetching data every 15 minutes

**Comment by caro-coder** [comment]
Every 15 minutes seems to be right. If you have dashboards in the field of view nearly all day this adds up 😄 Only reloading when events changed would be a big relieve!

**Comment by ljmerza** [comment]
ok try v3.92.3

**Comment by caro-coder** [comment]
Looks good to me on first sight. I'll check it on friday on my dashboards at home (I'm on tour at the moment) and give a final feedback. Thank you very much!

**Comment by caro-coder** [comment]
It's working! Thank you! :)
