### ISSUE TITLE
Expand ignoreEvents to also include location

### ISSUE THREAD

**Issue by edmuli** [ljmerza/calendar-card#53]
I have a case where I need to filter on location. I see the ignoreEvents checks on newEvent.title, if the check could be expanded to also include the location field, or just all fields, that would be very nice. Or perhaps specify in the filter query what fields you want to run the regex ignore on?

**Comment by ljmerza** [comment]
added in `v3.96.0` as `ignoreEventsByLocationExpression` option

**Comment by edmuli** [comment]
Wow! Thank you so much for a very quick feature add :)
