### ISSUE TITLE
calendar.### Response Error 400

### ISSUE THREAD

**Issue by CptKalibak** [ljmerza/calendar-card#54]
Hi,
I finally got everything going, but now I always have the Message calendar.### Response Error 400 with an exlamation point below the header.

Anyway I can get rid of this message?

**Comment by ljmerza** [comment]
one of your calendars is failing to load. Try disabling one calendar at a time to find out which one

**Comment by CptKalibak** [comment]
Ok! Thanks! That put me on Track. In the Lovelace Code while adding the Card. It put one Calendar as entity double in the code. This can only be seen in the Code of Lovelace not in your sweet overlay.
