### ISSUE TITLE
Hide timed events that already passed

### ISSUE THREAD

**Issue by Stooovie** [ljmerza/calendar-card#58]
Hello, I'd like a feature that would hide events whose time has already passed. Say, I don't need to see a morning event later that day. Thanks!

**Comment by ljmerza** [comment]
should be added in v3.98.0 via `hidePastEvents` option

**Comment by Stooovie** [comment]
That setting doesn't do anything on my setup though.

**Comment by lujkas** [comment]
Hi. I want to see the past events but when I set hidePastEvents = true, nothing happens and past events are still not visible.

**Comment by ljmerza** [comment]
You want to see them? Set to false

**Comment by lujkas** [comment]
Sorry man. I meant when it's set to hidePastEvents: false, I still don't see them.

**Comment by lujkas** [comment]
In Developer Tools Logs, I see some GET requests, which have some filters like 

&maxResults=20&singleEvents=true&timeMin=2020-03-07T00%3A00%3A00%2B00%3A00&timeMax=2020-06-15T00%3A00%3A00%2B00%3A00&alt=json. 
Do you think it has to do with timeMin?
