### ISSUE TITLE
Custom element doesn't exist: weather-card.

### ISSUE THREAD

**Issue by poudenes** [ljmerza/calendar-card#59]
Hello All,

The add-on was working for weeks. After a reboot of the HA system the add-on is not working anymore. The whole config / system is the same before and after the reboot.

I found this in the LOG file:
`https://<MY OWN URL/community_plugin/weather-card/weather-card.js:90:16 SyntaxError: expected dot, got '(`

Can someone help me with this?

**Comment by ljmerza** [comment]
this is the calendar card

**Comment by poudenes** [comment]
Sorry my mistake.
