### ISSUE TITLE
Broken in 0.86

### ISSUE THREAD

**Issue by DarkFox** [ljmerza/calendar-card#6]
The card breaks, seemingly because it's trying to use moment before it's loaded. 

~~Uncommenting~~ Commenting out line 23 (`moment.locale(hass.language);`) mostly fixes it, but breaks locale support.

**Comment by zerox1212** [comment]
I'm also looking for a more permanent fix. Only on rare occasions does the card load. In most cases it never shows up.

**Comment by rpitera** [comment]
> Uncommenting line 23 (moment.locale(hass.language);) mostly fixes it, but breaks locale support.

@DarkFox I assumed you meant to say to COMMENT out that line, as that fixed it for me.  At least to get a proper display.  Thanks for this temp solution, hope this gets fixed as it's one of my favorite cards.

**Comment by ljmerza** [comment]
Hmm that did happen to me a few times but now that I'm trying to reproduce it it's not happening. Honestly, This card needs to be rewritten from scratch. I just copied the original and updated a few things here and there but didn't know much about how Lovelace works at the time. I just finished another card so I plan to work on this one now. Hopefully within the next week I'll have an update.

**Comment by rpitera** [comment]
Seeing what you've been coming up with lately, I am looking forward to it!

**Comment by ljmerza** [comment]
The card has been rewritten. Please read the updated readme to use the new version.
