### ISSUE TITLE
Feature Request: Limit number of events

### ISSUE THREAD

**Issue by caro-coder** [ljmerza/calendar-card#60]
In addition to the "Number Of Days" limit, it would be nice to have a "Number Of Events" limit. In some weeks, I have only five events - then the card is very short - in other weeks, I have 30 events, so the card gets very very long. I can only limit the number of events in the google calendar settings per calendar, but that doesn't help if I have e.g. five calendars. If I have lots of events in one calendar, this one hits the limit very early, so I maybe can only see one day in this calendar, but five days in another.

With a events limit in the calendar card, I always get an even cut on all calendars. 

A bonus would be an "intelligent" limit: If my limit is 10 events and I have event number 10 & 11 on one day, the limit could either cut of that day completely (and only show until event 9 on the day before) or limit after that day (so show event 11 additionally). I think I'd go for the latter and I think that this one might be easier to accomplish if you go through the events in a loop. Then you can check if you hit the limit and compare the date with the date before - if that's the same, keep on looping until you reach the next day and then break the loop. (just my non-programmer-thoughts)

Thank you in advance!

**Comment by ljmerza** [comment]
added in v3.100.0. If the limit is reached then the rest of the day's events are shown

**Comment by caro-coder** [comment]
Thank you very much!
