### ISSUE TITLE
24h and "All day" settings

### ISSUE THREAD

**Issue by hwtiziani** [ljmerza/calendar-card#66]
First of all - really great job, its a very nice Calendar card ...
All i wonder if there is a ability to set time to 24h instead of AM/PM,
and, where to do the translation of "All day" ... Calendar card is showing the right language (de) in
months and day - names - exept of the above mentioned ...

Maybe i have a problem in reading , but i cant find any suggest in this issue ???

Thanks a lot for time

**Comment by ljmerza** [comment]
You can set the time format with `timeFormat` see the readme for a link to how to set that up. Unfortunately, translations for 'All day' aren't given to me, only for datetime related stuff like days of week.

**Comment by hwtiziani** [comment]
so, shame on me, is there a possibility to implement a variable-set similar to

`fullDayEventText: 'xxxxxxxxxx'`
`untilText: xxxxxxx'`

as found in atomic calendar ?

**Comment by ljmerza** [comment]
added in 3.101.0:

fullDayEventText
startText
endText
