### ISSUE TITLE
Problems with option "Show MultDay"

### ISSUE THREAD

**Issue by manuelo1983** [ljmerza/calendar-card#67]
If I have an date in my calendar from time e.g. 18:00 until 00:00 and the option Show MultDay is on, the entry in the calendar is not showing. When I deactivate this option, the entry is showing correctly, but then the problem ist, that dates which goes over more days are shown also not correctly. You only see the firt entry of e.g. three days.
Please help with this issue.
Thanks a lot!

**Comment by ljmerza** [comment]
from 18:00 to 00:00 on the same day? Would this not be a multi day event then?

**Comment by manuelo1983** [comment]
Yes it is a multi day event but When I Activate multi day event, the Entry from the calendar is not showing.

**Comment by ljmerza** [comment]
How is it a multiday event if the event only lasts from 18:00 to 00:00 the same day?

**Comment by manuelo1983** [comment]
Yes normally it is an event on one single day. But When I deactivate this Option events over more days are not showing correctly.

**Comment by manuelo1983** [comment]
Is there any possiblility do fix this issue? I tried again to set an date from 16:00 till 00:00 and the entry is not showing. If I enter 00:05 it is showing. Also wenn it is before 00:00 e.g. 23:55.
Thank you

**Comment by ljmerza** [comment]
taking a look at this again. might just have to rewrite the way dates are handled though but I can reproduce the issue

**Comment by ljmerza** [comment]
ok think i got this figured out in v3.108.2

**Comment by manuelo1983** [comment]
that sounds good

**Comment by manuelo1983** [comment]
I have tried both. it works fine. thank you
