### ISSUE TITLE
Add height to card

### ISSUE THREAD

**Issue by wbilger** [ljmerza/calendar-card#69]
This is a feature request, but would it be easy to add a height to the card and have the card scrollable.
Right now I achieve it by creating a view for just the calendar (using cch hide header), then showing that view in a iframe, and it looks perfect, but it is not ideal with reloads (every time go back to view the iframe reloads).

**Comment by wbilger** [comment]
FYI, I was able to accomplish this by editing the css with the card-mod custom card by Thomas Loven.
Using the following code, but it would still be nice if it was built in.

style: |
  ha-card {
    height: 251px 
  }
  ha-card {
    overflow: scroll
  }

**Comment by ljmerza** [comment]
added maxHeight option in 3.101.0
