### ISSUE TITLE
UI Editor

### ISSUE THREAD

**Issue by iantrich** [ljmerza/calendar-card#7]
Can now add UI Editors to custom cards. e.g. my [Roku Card](https://github.com/custom-cards/roku-card/blob/master/roku-card-editor.js)

**Comment by ljmerza** [comment]
I'll have to look into this, I'm not familiar with how this works. Thanks for the suggestion.

**Comment by iantrich** [comment]
Sounds like you're going to be doing a rewrite to lit soon, should be really easy then

**Comment by ljmerza** [comment]
Added editor card

**Comment by iantrich** [comment]
🎉
