### ISSUE TITLE
Hide past days in multiple days events doesn't work right

### ISSUE THREAD

**Issue by noxhirsch** [ljmerza/calendar-card#70]
Hi,
at first thank you for implementing my suggestion from #65!
Sadly it doesn't seem to work right :( 
![calendar](https://user-images.githubusercontent.com/30938717/70211379-33eb8500-1735-11ea-981f-e0e78799c124.PNG)
 This screenshot is from today (5.12.) and it looks like only the first day of the multi day event got stripped (all caches cleared).

**Comment by ljmerza** [comment]
ok I think I got it figured out in v3.101.1

**Comment by noxhirsch** [comment]
Yes, now it's working fine! Thank you very much :)
