### ISSUE TITLE
eventsLimit not working

### ISSUE THREAD

**Issue by Korte68** [ljmerza/calendar-card#72]
I have 7-8 events on every day and would like to see the 3 upcoming events, but it show all the events  for the day. 
Please solve it. Thank you

**Comment by Korte68** [comment]
It would be great if this function is interworking with the hidepastevents function... so if I have 11 events, and set the limit to 3, and the past events is hided, than it should show always the next 3 remaining events.

**Comment by ljmerza** [comment]
the default behavior of `eventLimits` will still show all events for that day, even if they go over the limit set. For backwards compatibility, I added `hardLimit` option in v3.103.0 that will respect the `eventsLimit` even for events on the same day.

**Comment by Korte68** [comment]
Working! Thank you!
