### ISSUE TITLE
HACS update

### ISSUE THREAD

**Issue by dolenec** [ljmerza/calendar-card#76]
Update via HACS on Home Assistant is not working. Every other component is uodating normally - only Calendar Card not..

**Comment by ljmerza** [comment]
do you use any of my others cards and do they update? light-entity, travel-time, github, reddit, fitbit, tracking-number, our-groceries. I looked at the HACS docs and doesn't seem like anything has changed recently. As a dev, I use my local development version so I don't load my own cards through HACS

**Comment by ljmerza** [comment]
i just bumped the version to test HACS and it worked fine on my end. when you say its not working, what do you mean? do you click update and it still shows the old version in HACS after you reload

**Comment by kugan49** [comment]
the message in log :
`ERROR (MainThread) [hacs.repository.plugin.ljmerza.calendar-card] Download was not complete.`

this message is from [repository.py](https://github.com/hacs/integration/blob/master/custom_components/hacs/repositories/repository.py ) line 495 : 

`async def download_zip(self, validate):
        """Download ZIP archive from repository release."""
        try:
            contents = False

            for release in self.releases.objects:
                self.logger.info(f"ref: {self.ref}  ---  tag: {release.tag_name}")
                if release.tag_name == self.ref.split("/")[1]:
                    contents = release.assets

            if not contents:
                return validate

            for content in contents or []:
                filecontent = await async_download_file(self.hass, content.download_url)

                if filecontent is None:
                    validate.errors.append(f"[{content.name}] was not downloaded.")
                    continue

                result = await async_save_file(
                    f"{tempfile.gettempdir()}/{self.repository_manifest.filename}",
                    filecontent,
                )
                with zipfile.ZipFile(
                    f"{tempfile.gettempdir()}/{self.repository_manifest.filename}", "r"
                ) as zip_file:
                    zip_file.extractall(self.content.path.local)

                if result:
                    self.logger.info(f"download of {content.name} complete")
                    continue
                validate.errors.append(f"[{content.name}] was not downloaded.")
        except Exception:
            validate.errors.append(f"Download was not complete.")`

**Comment by reharmsen** [comment]
I am also seeing this issue

**Comment by dolenec** [comment]
When I click update it start updating.. then compomemt.download counter go +1 and then nothing happens. Version number is not updated. And you can click this many times - I tried.. So download counter is 100% incorrect..

**Comment by dolenec** [comment]
Same problem with 104 version..

**Comment by ljmerza** [comment]
ok, thanks for the info. Looks like HACS is throwing away the details of the error so I can't see what's even going on. I've requested for HACS be updated to provide more information for failures in that area. I'll still debug on my end and see what's going on.

**Comment by ljmerza** [comment]
Looks like they made an update to HACS that hopefully fixes this issue, try updating to the latest version and let me know if it works.

**Comment by dolenec** [comment]
I can confirm that now its working..
