### ISSUE TITLE
Feature Request: Show the age on birthdays

### ISSUE THREAD

**Issue by jankete** [ljmerza/calendar-card#79]
Hi,
Google uses a calendar for storing the birthdays of our contacs. It uses an appointment series which starts at the date of birth (including the year). With this information, would it be possible to show the age of a contact on the card?

![image](https://user-images.githubusercontent.com/22338766/72499792-21d02c80-3833-11ea-810c-484a2f0d0199.png)

**Comment by ljmerza** [comment]
The Google Calendar API doesn't give this type of information so there's no way to add this feature, sorry.
