### ISSUE TITLE
Feature Request: Hide string from output

### ISSUE THREAD

**Issue by jankete** [ljmerza/calendar-card#80]
Hi,
would it be possible to hide / suspress some string from being displayed? I use the card for showing the birthday calendar from google and would like to hide the "hat Geburtstag" so that only the name is shown.

![image](https://user-images.githubusercontent.com/22338766/72499979-9c00b100-3833-11ea-939f-d873c91eb89c.png)

**Comment by ljmerza** [comment]
added in v3.106.0 as `removeFromEventTitle`
