### ISSUE TITLE
Declined meetings still showing up

### ISSUE THREAD

**Issue by jkrall** [ljmerza/calendar-card#81]
I have several calendars with meetings that I have declined, and therefore will not be attending... but these events still show up in the card list alongside the rest of my events.

Looking at the raw event payload being sent from HA, It appears there is an `attendees` key that contains this information:
```
{
attendees: [{email: "someone@something.com", responseStatus: "declined"},…],…}
}
```

I'm guessing an implementation of this feature would need to know what email address is associated with that calendar, so that it could grab the proper attendee and check the `responseStatus`.

I'd be happy to take a hack at implementing this -- but I don't have any experience with lovelace development.  If someone could point me at a primer on how to setup a dev environment so I could iterate on this, I might be able to make these changes myself and submit a PR.

**Comment by ljmerza** [comment]
added in `v3.105.0` via the `hideDeclined` option
