### ISSUE TITLE
Authorisation problem response error 400

### ISSUE THREAD

**Issue by manuelo1983** [ljmerza/calendar-card#84]
Hello, I have a problem with the authorisation to the google calendar. It worked fine and on the next day I got the error "response error: 400". In the log I only can see, that there is a authorisation problem. I have checked all data in the config. Everything is fine.
Please can everybody help me. Thanks

**Comment by manuelo1983** [comment]
I find out, that I cannot see all calendars in the selection. I have one family calendar, but this is not as entity in the calendar card.

**Comment by ljmerza** [comment]
this card pulls from home assistant so the auth error is coming from home assistant. check if you can see them in the entities table and can see the next event in the state

**Comment by manuelo1983** [comment]
I have found the problem. I had to rename the .google.token in the configuration folder. And then I have to reauth home assistant new. Now it works. thank you
