### ISSUE TITLE
Feature Request: Sensor of first upcoming event

### ISSUE THREAD

**Issue by poudenes** [ljmerza/calendar-card#85]
Hi All,

Would be so nice to have sensor that will give the first event in list based on time and date.
Example I have a appointment:

`18-02-2020 at 12:00 hour, subject: example`

I have beside the calendar card a sensor that shows:

`12:00`

What I can do then is create a automation that it will turn on lights X minutes or hours before that sensor time. And let Alexa of Google hear e siren as alarm to get up. :) 

Never put the alarm manual anymore then on phone or what ever.

**Comment by ljmerza** [comment]
The calendar sensor built into ha should have the next event as it's state. This is only a lovelace card and cannot create a sensor or state.

**Comment by poudenes** [comment]
Can you assist me then how to use it in a automation?

**Comment by ljmerza** [comment]
try to home assistant discord
