### ISSUE TITLE
Custom element doesn't exist: calendar-card.

### ISSUE THREAD

**Issue by DesertDwellerEv** [ljmerza/calendar-card#87]
Not working.
![image](https://user-images.githubusercontent.com/53842308/76109174-2db9ae80-5f99-11ea-908e-921c459d0415.png)

Saw this when I upgraded
[Changes that can affect custom cards in 0.106](https://developers.home-assistant.io/blog/2020/02/18/106-custom-card-changes/)

**Comment by ljmerza** [comment]
works for me just fine im on 106.5. make sure it's installed correctly. none of the breaking changes in 106 affect this card

**Comment by alloydwhitlock** [comment]
Fresh install via HACS shows it's looking for artifacts in the dist directory
```
home-assistant.log:2020-03-07 10:14:53 ERROR (MainThread) [hacs] Tried to serve up '/config/www/community/calendar-card/dist/calendar-card.js' but it does not exist
```

**Comment by DesertDwellerEv** [comment]
Reinstalled and got the following error log entry:
Log Details (ERROR)

Logger: hacs
First occured: March 6, 2020, 11:04:12 AM (5 occurences)
Last logged: 9:45:27 AM

Tried to serve up
'/config/www/community/calendar-card/dist/calendar-card.js' but it
does not exist

**Comment by ljmerza** [comment]
so the file doesn't exist in that directory? Sounds like its not being installed correctly from HACS. Should be /hacsfiles/ path

**Comment by poudenes** [comment]
Update to latest version v3.1.0 get same error. Change the path no result. Clear cache no result. Funny in Chrome its working correct. Error only on Safari

When revert back to 3.0.0 everything is working again.

HA 0.106.4

**Comment by DesertDwellerEv** [comment]
I'm also running chrome. Still have the have issue.

**Comment by poudenes** [comment]
When I add them automatic via HACS I see this line

```
  - type: module
    url: /hacsfiles/calendar-card/dist/calendar-card.js
```

Even then its not working.

Also tried to remove /dist/ because that is not actual there in the folder. Did not work also

**Comment by Pirol62** [comment]
But: My calendar card is working in
````
- url: /community_plugin/calendar-card/calendar-card.js
    type: js
````
No issues. Only the hacs entry shows, that the plugin is not added to lovelace.

**Comment by ljmerza** [comment]
HACS is having issues on their end with proper importing. Looks like they released another fix today but if this still happens after upgrading, open an issue with them.

**Comment by DesertDwellerEv** [comment]
After update and removing dist folder from path, seems to be working.

**Comment by PierreScerri** [comment]
Removing /dis folder from path is not working for me.

**Comment by DesertDwellerEv** [comment]
This works for me now.
Yaml: 
  - type: module
    url: /hacsfiles/calendar-card/calendar-card.js
Install path:
/config/www/community/calendar-card/calendar-card.js

**Comment by PierreScerri** [comment]
Nope!

Removes the first error but gives this:

Logger: frontend.js.latest.202002205
First occured: 5:13:55 PM (2 occurences)
Last logged: 5:14:00 PM

http://homeassistant.local:8123/lovelace/0:0:0 Uncaught

**Comment by poudenes** [comment]
@PierreScerri I get the same error...
@ljmerza can you reopen this?

**Comment by ljmerza** [comment]
Do not use HACS and install manually. They has issues they need to work out.

**Comment by PierreScerri** [comment]
This update fixes the issue:

https://github.com/hacs/integration/releases/tag/0.23.2

**Comment by ljmerza** [comment]
They've had a few releases fixing imports. Hopefully this last release squashed any bugs on this issue for good.
