### ISSUE TITLE
Margin left in calendar items

### ISSUE THREAD

**Issue by balonchiks** [ljmerza/calendar-card#88]
Hi, would that be possible to add the left margin to the calendar items like you have on the screenshot in description:
![image](https://user-images.githubusercontent.com/31212478/76404584-fc6d2400-6386-11ea-9342-6282e208b0d3.png)

Because right now it is aligned to the left, in line with the title, and all the other lovelace cards do have a slight margin:

![image](https://user-images.githubusercontent.com/31212478/76404542-eeb79e80-6386-11ea-8384-31f04660ad3d.png)

**Comment by ljmerza** [comment]
added in v3.108.4
