### ISSUE TITLE
Uneven position with v3.108.4

### ISSUE THREAD

**Issue by noxhirsch** [ljmerza/calendar-card#89]
Hi,
in v3.108.4 you added a margin-left of 10px. Now, the calendar is moved to the right as you can see with the divider line:
![image](https://user-images.githubusercontent.com/30938717/76562365-890e0400-64a5-11ea-80d3-2f723644a364.png)
I'd prefer the old position (because it's more space efficiant) or there should be at least a margin-right to equal the margins.
Thank you very much!
Nico

**Comment by ljmerza** [comment]
removed margin in v3.108.6
