### ISSUE TITLE
Custom element doesn't exist: calendar-card.

### ISSUE THREAD

**Issue by mpejstrup** [ljmerza/calendar-card#91]
Hi

Just installed your card today. 
Have installed via HACS and is running HA in Docker on RPI4+.
![2020-03-28_12h31_40](https://user-images.githubusercontent.com/55014016/77822113-15e4ce80-70f0-11ea-9105-5b9d3a3f5f7a.png)
My other custom cards are running fine. 

In resources.yaml:
- url: /hacsfiles/calendar-card/calendar-card.js
  type: module

In lovelace.yaml
#Kalender
              - type: custom:calendar-card
                progressBar: true
                entities: 
                  - calendar.martin
                  - calendar.kalender
                title: Kalender
                numberOfDays: 5
                showLocation: true

Am I misunderstading your instructions or is it an issue with the last update?

**Comment by ljmerza** [comment]
there are no issues with installing this card. check that the card has been correctly installed via HACS. They've had a lot of issue with this lately.
