### ISSUE TITLE
Feature Request:  Divider Color

### ISSUE THREAD

**Issue by ttaidapos** [ljmerza/calendar-card#93]
Possible to have divider color not use "primary-text-color" have it's own value.  Hard to theme with text and divider being the same color.

![image](https://user-images.githubusercontent.com/27898709/79355501-5d969300-7f03-11ea-90f8-53afe1994bb8.png)

**Comment by ljmerza** [comment]
added color to divider in v3.108.6

**Comment by ttaidapos** [comment]
> added color to divider in v3.108.6

Awesome that was quick!  Where can I edit (file_name) the divider color?  Gave a glance on latest updated files but couldn't find it in the latest release.
