### ISSUE TITLE
Tried to serve up '/config/www/community/calendar-card/dist/calendar-card.js' but it does not exist

### ISSUE THREAD

**Issue by amblyo** [ljmerza/calendar-card#97]
Got this error in 3.108.6

Logger: hacs
Source: custom_components/hacs/http.py:76
First occurred: 16:22:27 (1 occurrences)
Last logged: 16:22:27

Tried to serve up '/config/www/community/calendar-card/dist/calendar-card.js' but it does not exist

**Comment by ljmerza** [comment]
`/config/www/community` is the depreciated path. Look into the HACS docs to see how to reinstall
