### ISSUE TITLE
Strange Colors in Lovelace GUI

### ISSUE THREAD

**Issue by breti** [ljmerza/calendar-card#98]
Hi there, 

Calendar Card is working fine, thanks a lot! 

However I'm not sure if the colors of the divider and the progress indicator of the event are intended that way (orange)? HA default theme, no theme customizations.

![grafik](https://user-images.githubusercontent.com/3628895/81849792-54770100-9557-11ea-977b-91008059b6c5.png)

**Comment by ljmerza** [comment]
its the secondary color of your theme
